version: '3.4'

services:
  shopping.api:
    container_name: shoppingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://shopping.db:27017"
    depends_on:
       - shopping.db

    ports:
      - "8000:80" #arrange port # of container 

  shoppnig.client:
    container_name: shoppingclient
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ShoppingAPIUrl=http://shoppingapi"
    ports:
      - "8001:80" #arrange port # of container 
    depends_on:
      - shopping.api
      - shopping.db 

  shopping.db:
    container_name: shoppingdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db 

